### PR TITLE
Adds support for MS Teams natively using webhooks

### LINKED ISSUE #134: Feature to support Microsoft Teams channels
We need an out of the box support for Microsoft Teams channels. I can make a Pull Request for this. 👌

### PR DESCRIPTION
**Pull request by vaamarnath**
MS Teams is now natively integrated with Kubewatch. The configuration
can be provided for posting on to the MS Teams incoming webhook
connector.

The implementation is inspired from the MS Teams and Prometheus
alerts integration by https://github.com/bzon/prometheus-msteams

Fixes #134

### CODE REVIEW

**Comment by dmarkey** [comment]
Any reason this cant go on?

**Comment by jseguillon** [comment]
hi all. just noticed this usefull PR was never merged. Is there any chance some of you guys merge this ? 

cc @tylerauerbeck (?)

**Comment by rvdh** [comment]
@jbianquetti-nami @tylerauerbeck @aruiz14 @mkmik Please have a look at this PR, we would love MS Teams integration!

**Comment by jbianquetti-nami** [comment]
if @vaamarnath fixes the conflict I'll take a look at this. Thanks for the pointer.

**Comment by vaamarnath** [comment]
I will resolve the conflicts and update the PR soon. Thanks for your patience!

**Comment by vaamarnath** [comment]
@jbianquetti-nami PTAL. I have resolved the conflicts. Thanks!

**Comment by vaamarnath** [comment]
Thanks for you review @jbianquetti-nami. 

Please merge this whenever you got time @jbianquetti-nami @tylerauerbeck @aruiz14 @mkmik.

**Pull request merged**
