### PR TITLE
Enable setting a custom title for the slack messages

### PR DESCRIPTION
**Pull request by mtougeron**
This PR allows setting a `title` field for Slack messages so that when you run `kubewatch` in multiple clusters you can identify which cluster the messages are coming from.

### CODE REVIEW

**Comment by mtougeron** [comment]
Is there anyone who could possibly review this small change? Thanks.

**Comment by AkshayDubey29** [comment]
Can anyone please merge this if this is fine, I needed this functionality

**Comment by mtougeron** [comment]
Is there anyone that can review/merge this PR for me? Thanks!

**Comment by mtougeron** [comment]
Is there anyone that can review this please?

**Comment by fgeorgatos** [comment]
i gave it a visual check, lgtm

**Comment by bjorn-ali-goransson** [comment]
LGTM

**Pull request merged**
